### ISSUE TITLE
openmediavault-backup 6.0.1: Backup Plugin not showing current settings in WebGUI

### ISSUE THREAD

**Issue by Fabeson** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#64] opened 2022-01-02 12:39 UTC
I am using openmediavault-backup 6.0.1 on 6.0.6-1 (Shaitan)

When configuring an OS backup in the plugin webGUI (<serverAddress>/#/system/backup), the chosen settings are correctly written into /etc/openmediavault/config.xml - However, the GUI always shows the default plugin values and eg. loses the selected Share. See screenshots for direct comparison

![Backup GUI](https://user-images.githubusercontent.com/26404897/147875931-5f32ec81-8fe4-41db-95f0-a4f1f07a9e2d.png)
![config xml](https://user-images.githubusercontent.com/26404897/147875932-b59bd301-d277-4924-a3a1-69c6662aad60.png)

**Comment by ryecoaaron** [comment] 2022-01-02 14:18
I still trying figure out why this is happening. Closing as duplicate of https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-backup/issues/31

**Closed by ryecoaaron** 2022-01-02 14:18 UTC
