### ISSUE TITLE
Couple of issues with Symlinks plugin

### ISSUE THREAD

**Issue by ken8521** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#61] opened 2021-11-01 23:41 UTC
Testing the symlink plugin on a virtual machine and ran into a couple problems.  While trying to add a symlink...  When I click the button to add a source or destination, I get the following error... 

'500 - Internal Server Error  Failed to execute XPath query '//system/fstab/mntent[uuid=79684322-3eac-11ea-a974-63a080abab18']

Not sure where that UUID is coming from as not it's even referenced on my system.

root@omv6-test:/srv# ls
dev-disk-by-uuid-4e5f57a4-380b-4b40-92ba-363b0fbbd484  ftp     salt
dev-disk-by-uuid-7d1952b0-2283-4e3c-b8df-04b50f5f1991  pillar
root@omv6-test:/srv# 

`root@omv6-test:~# blkid
/dev/sda1: UUID="25fed6cf-c751-4913-83dd-518f9eebca19" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="53a2c4b6-01"
/dev/sda5: UUID="c5dd9627-b480-48f1-8dbb-5c728faddaec" TYPE="swap" PARTUUID="53a2c4b6-05"
/dev/sdb1: UUID="4e5f57a4-380b-4b40-92ba-363b0fbbd484" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="bc3177cb-b29f-4da6-90d9-7fc151bbd5e1"
/dev/sdc1: UUID="7d1952b0-2283-4e3c-b8df-04b50f5f1991" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="5d55651a-0e7a-4a41-84c1-13db7461bed4"
root@omv6-test:~# 
`
If I type the paths in the plugin manually, it works fine.

Issue #2 (maybe this should be a separate post?) If (for example) I enter one of the paths wrong, and try to edit... I get the black screen/red message stating "Software Error:  Left Mouse to Continue.  The requested page was not found".. which then just takes me back to the webUI.  I can delete the symlink and just recreate it (so long as I manually type it given the other issue) and it works just fine.

Both issues happen on Firefox and Chrome.

Let me know if you need anything else to troubleshoot.

**Comment by ryecoaaron** [comment] 2021-11-02 00:00
For future issues, please post on the symlinks repo - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-symlinks/issues

You need to install the openmediavault-sharerootfs plugin (install from the Plugins tab)  if you want the directory browser to work.  I guess I need to make that a dependency of the plugin.

Your second issue is caused by the sharerootfs plugin not being installed as well.

**Comment by ken8521** [comment] 2021-11-02 00:08
My mistake :)... 

It works now.  Thanks

**Comment by ryecoaaron** [comment] 2021-11-02 00:14
Fixed in this commit - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-symlinks/commit/521ff64ae0a89dc9d060a1369411f547fbb42901.  I will push an update when I get a chance.

**Closed by ryecoaaron** 2021-11-02 00:14 UTC
