### ISSUE TITLE
Please disable write docker source to sourcelist when installing OMV from Debian

### ISSUE THREAD

**Issue by PP88PP** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#79] opened 2023-02-11 14:08 UTC
When Docker installed before install OMV6.3, OMV installtion will get errors about apt-get update get docker gpg errors. Then some packages setted to install after OMV write Docker to sourcelist will not be installed.
OMV's docker cannot succesfully installed to my OS, So I need install the docker manully which not in OMV's source.

**Comment by ryecoaaron** [comment] 2023-02-11 14:15
What error?  You are not giving me any information.

**Comment by ryecoaaron** [comment] 2023-02-11 14:15
And docker is in the Debian repos.  The package is named docker.io.

**Comment by ryecoaaron** [comment] 2023-02-11 14:17
You also can already disable the docker repo in omv-extras.  Just set the OMV_DISABLE_DOCKER environment variable to true or 1.  https://docs.openmediavault.org/en/5.x/various/advset.html

**Comment by PP88PP** [comment] 2023-02-11 14:18
> What error?  You are not giving me any information.

About what? apt-get update gpg errors, or OMV's docker install failed?

**Comment by ryecoaaron** [comment] 2023-02-11 14:20
Why not give both?  Hundreds of people are installing docker with omv-extras and not having an issue.

**Comment by PP88PP** [comment] 2023-02-12 05:46
> Why not give both? Hundreds of people are installing docker with omv-extras and not having an issue.

install Docker first then install OMV, aptitude update
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bullseye: /etc/apt/keyrings/docker.gpg !=
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bullseye: /etc/apt/keyrings/docker.gpg !=
E: The list of sources could not be read.
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bullseye: /etc/apt/keyrings/docker.gpg !=
E: The list of sources could not be read.
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bullseye: /etc/apt/keyrings/docker.gpg !=
E: Couldn't read list of package sources

omv-env set -- OMV_DISABLE_DOCKER 1 and apply change. Purge containerd.io docker-ce docker-ce-cli docker-compose-plugin, then install docker via sh from https://get.docker.com
# Executing docker install script, commit: 66474034547a96caa0a25be56051ff8b726a1b28
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c mkdir -p /etc/apt/keyrings && chmod -R 0755 /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ryecoaaron** [comment] 2023-02-12 13:07
> install Docker first then install OMV,

If you read the [install guide](https://forum.openmediavault.org/index.php?thread/28789-installing-omv6-or-omv5-on-raspberry-pi-s-armbian-sbc-s-i386-32-bit-platforms/), you wouldn't install docker first.  And there is no reason to run the docker install script if you install docker from the omv-extras Docker tab (the do the same thign).  By running the docker install script and installing omv-extras, you are causing the duplicate conflict.

Since this is not a bug, closing.

**Closed by ryecoaaron** 2023-02-12 13:07 UTC
